apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins
rules:
- apiGroups:
  - '*'
  resources:
  - statefulsets
  - services
  - replicationcontrollers
  - replicasets
  - podtemplates
  - podsecuritypolicies
  - pods
  - pods/log
  - pods/exec
  - podpreset
  - poddisruptionbudgets
  - persistentvolumes
  - persistentvolumeclaims
  - jobs
  - endpoints
  - deployments
  - deployments/scale
  - daemonsets
  - cronjobs
  - configmaps
  - namespaces
  - events
  - secrets
  - customresourcedefinitions
  - clusterroles
  - clusterrolebindings
  - servicemonitors
  - networkpolicies
  - limitranges
  - resourcequotas
  - horizontalpodautoscalers
  - certificatesigningrequests
  - leases
  - ingresses
  - storageclasses
  - volumeattachments
  verbs:
  - create
  - get
  - watch
  - delete
  - list
  - patch
  - update
  - use
  - '*'
- apiGroups:
  - ""
  resources:
  - nodes
  - serviceaccounts
  - services/finalizers
  - configmaps
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
  - '*'
- apiGroups:
  - "admissionregistration.k8s.io"
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - list
  - watch
- apiGroups:
  - "autoscaling"
  resources:
  - horizontalpodautoscalers
  verbs:
  - list
  - watch
- apiGroups:
  - "certificates.k8s.io"
  resources:
  - certificatesigningrequests
  verbs:
  - list
  - watch
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - list
  - watch
- apiGroups:
  - "extensions"
  resources:
  - ingresses
  verbs:
  - list
  - watch
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - list
  - watch
- apiGroups:
  - "storage.k8s.io"
  resources:
  - storageclasses
  - volumeattachments
  verbs:
  - list
  - watch
- apiGroups:
  - "monitoring.coreos.com"
  resources:
  - alertmanagerconfigs
  - alertmanagers
  - alertmanagers/finalizers
  - alertmanagers/status
  - podmonitors
  - probes
  - prometheusagents
  - prometheusagents/finalizers
  - prometheusagents/status
  - prometheuses
  - prometheuses/finalizers
  - prometheuses/status
  - prometheusrules
  - scrapeconfigs
  - servicemonitors
  - thanosrulers
  - thanosrulers/finalizers
  - thanosrulers/status
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-demo-metrics
  namespace: demo-metrics
rules:
- apiGroups: [""]
  resources: ["secrets", "serviceaccounts", "limitranges", "resourcequotas", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "*"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch", "*"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["alertmanagers", "prometheuses", "servicemonitors", "alertmanagerconfigs", "prometheusrules", "thanosrulers", "podmonitors", "probes", "scrapeconfigs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-demo-metrics
  namespace: demo-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-demo-metrics
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: jenkins