name: 'Helm - Validations'

env:
  HELM_CHART: "jenkins-ci"

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  lint-with-dry-install:
    name: 'Helm: Lint with Dry Run Installation'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Helm dependency update
        id: dependency-update
        run: |
          helm dependency update ${{ env.HELM_CHART }}

      - name: Helm dependency list
        id: dependency-list
        run: |
          helm dependency update ${{ env.HELM_CHART }}

      - name: Run lint
        id: fmt
        run: helm lint ${{ env.HELM_CHART }}